url = "https://customerportal.supermicro.com/SO/CustOrders.aspx"
orderType = "//select[@id='ContentPlaceHolder1_ddlSearchType']"
fromDate = "//input[@id='ContentPlaceHolder1_txtFrom']"
customerId = "//select[@id='ContentPlaceHolder1_ddlCustomerID']"
searchIcon = "//a[@id='linkSearch']"
orderTable = "//table[contains(@id,'ContentPlaceHolder1')]"
pageCount = "(//tr[@class='gridPager']/td/table/tbody/tr/td)"
selectPage = "(//tr[@class='gridPager']/td/table/tbody/tr/td)[{}]"
soldToAddress = "//td[@class='InfoCell AddressCell ']/div/div/div[{}]"
shipToAddress = "//td[@class='InfoCell AddressCell']/div/div/div[{}]"
esd = "//td[@class='InfoCell ETACell']"
message = "//td[@class='InfoCell CommentsCell']"
orderItem = "//div[contains(@id,'panelOrdItemList')]/div/a"
orderItemHeaders = "//table[contains(@id,'gvOrdDetails')]/tbody/tr[1]/th"
orderItemRows = "//table[contains(@id,'gvOrdDetails')]/tbody/tr"
orderItemRowsValue = "//table[contains(@id,'gvOrdDetails')]/tbody/tr[{}]/td[{}]"
orderItemHeadersValue = "//table[contains(@id,'gvOrdDetails')]/tbody/tr[1]/th[{}]"


closeOrderTableRowCount = "//table[@id='ContentPlaceHolder1_gvCloseOrd']/tbody//tr"
closeOrderSalesOrder = "//table[@id='ContentPlaceHolder1_gvCloseOrd']/tbody//tr[{}]/td[1]"
closeOrderOrderData = "//table[@id='ContentPlaceHolder1_gvCloseOrd']/tbody//tr[{}]/td[2]"
closeOrderCustomerPO = "//table[@id='ContentPlaceHolder1_gvCloseOrd']/tbody//tr[{}]/td[3]"
closeOrderAssemblyType = "//table[@id='ContentPlaceHolder1_gvCloseOrd']/tbody//tr[{}]/td[4]"
closeOrderOrderDetailsButton = "//table[@id='ContentPlaceHolder1_gvCloseOrd']/tbody//tr[{}]/td[6]/a"
closeOrderOrderStatus = "//table[@id='ContentPlaceHolder1_ClosedOrdInfo_gvOrdHeader']//tr[2]/td[6]"

openOrderTableRowCount = "//table[@id='ContentPlaceHolder1_gvOpenOrd']/tbody//tr"
openOrderSoldToId = "//table[@id='ContentPlaceHolder1_gvOpenOrd']/tbody//tr[{}]/td[1]"
openOrderSalesOrder = "//table[@id='ContentPlaceHolder1_gvOpenOrd']/tbody//tr[{}]/td[2]"
openOrderCustomerPO = "//table[@id='ContentPlaceHolder1_gvOpenOrd']/tbody//tr[{}]/td[3]"
openOrderShipToParty = "//table[@id='ContentPlaceHolder1_gvOpenOrd']/tbody//tr[{}]/td[4]"
openOrderShipToCountry = "//table[@id='ContentPlaceHolder1_gvOpenOrd']/tbody//tr[{}]/td[5]/div"
openOrderCreatedTime = "//table[@id='ContentPlaceHolder1_gvOpenOrd']/tbody//tr[{}]/td[6]"
openOrderOrderDetailsButton = "//table[@id='ContentPlaceHolder1_gvOpenOrd']/tbody//tr[{}]/td[7]/a"
openOrderAssemblyType = "//table[@id='ContentPlaceHolder1_gvOrdHeader']/tbody//tr[2]/td[2]"
openOrderOrderStatus = "//table[@id='ContentPlaceHolder1_gvOrdHeader']/tbody//tr[2]/td[6]"
